openapi: 3.0.3

info:
  title: Memo API
  description: Ensemble de bout de code
  contact:
    name: hussard
  version: 0.1.0

tags:
  - name: FizzBuzz

servers:
  - url: http://localhost:8080
    description: Local development environment
paths:
  /fizzbuzz:
    get:
      operationId: fizzbuzz
      description: execute le Kata FizzBuzz.
      tags:
        - FizzBuzz
      parameters:
        - in: query
          name: value
          schema:
            type: integer
          required: true
          description: valeur reçue
      responses:
        200:
          description: Retour une chaine de caractere.
          content:
            application/json:
              resultat:
                type: string
