openapi: "3.0.3"
info:
  version: 0.1.0
  title: Memo API
  description: Ensemble de bout de code
  contact:
    name: hussard
tags:
  - name: fizzbuzz
servers:
  - url: http://localhost:8080
    description: Local development environment
paths:
  /katas/fizzbuzz:
    get:
      tags:
        - fizzbuzz
      operationId: getFizzbuzz
      description: Execute le Kata FizzBuzz.
      parameters:
        - $ref: './parameters/query/fizzbuzzInput.yaml'
      responses:
        200:
          description: Retour une chaine de caractere.
          content:
            application/json:
              schema:
                $ref: './schemas/fizzbuzzDto.yaml'
        default:
          $ref: './responses/UnexpectedError.yaml'

